# Generated by Django 3.2.7 on 2021-10-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211010_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'uncompleted'), (1, 'completed')], default=0),
        ),
    ]
